apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  labels:
    env: dev
  namespace: default
spec:
  selector:
    env: dev
  # No need to explicitly specify the type.
  type: ClusterIP # By default it creates ClusterIP.
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80