apiVersion: v1
kind: Service
metadata:
  name: external-api
  namespace: default
spec:
  selector:
    env: dev
  type: ExternalName
  externalName: example.com #httpbin.org
  ports:
    - protocol: TCP
      port: 80