apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    env: dev
  namespace: default
spec:
  selector:
    env: dev
  type: NodePort
  ports:
    - nodePort: 30080
      protocol: TCP
      port: 80
      targetPort: 80
  
