apiVersion:  v1
kind: Pod
metadata:
  name: init-container
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: busybox:latest
      command: ['sh', '-c', 'echo the app is running && sleep 3600']
      env:
        - name: FIRSTNAME
          value: "test"
        - name: FETCH_VALUE
          valueFrom:
            configMapKeyRef:
              name: testmap
              key: testdata
        ## It is one way to do, but no useful and we can't access file becuase it did not mount to the container.
        ## This way only works for key value string type variables.
        - name: FROM_CM
          valueFrom:
            configMapKeyRef:
              name: testmap
              key: index.template.html
      # This is the best way to find and access.
      # check in the pod at /config
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: testmap