apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    env: test  # another example (app: dev) # key: value are customised and our wish to define.
spec:
  replicas: 3
  selector:
    matchLabels:
      env: test # another example (app: dev) # key: value are customised and our wish to define.
  template:
    metadata:
      name: nginx-rs
      labels:
        env: test
        type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80